name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Atualizar pip e instalar dependências Python
        run: |
          python -m pip install --upgrade pip

      - name: Executar testes com unittest
        run: |
          python -m unittest discover app/tests